[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

### This entire setup is pretty much carbon copied by ENNWAY's setup for murder joker. (I don't actually know frowned upon this is - MaxBoi)

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''
function love.update( dt )
'''
position = "after"
payload = '''
SCP.update()
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
if G.SPLASH_FRONT then
            love.graphics.push()
            G.SPLASH_FRONT:translate_container()
            G.SPLASH_FRONT:draw()
            love.graphics.pop()
        end
'''
position = "after"
payload = '''
SCP.draw()
'''
match_indent = true
times = 1