[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# win on any ante past win ante
[[patches]]
[patches.pattern]
target = '''functions/state_events.lua'''
pattern = '''
if G.GAME.round_resets.ante == G.GAME.win_ante and G.GAME.blind:get_type() == 'Boss' then
'''
position = 'before'
match_indent = true
payload = '''
if G.GAME.round_resets.ante >= G.GAME.win_ante and G.GAME.blind:get_type() == 'Boss' then
    game_won = true
    G.GAME.won = true
end
'''